pipeline{
    agent Any
    stages{
        stage('git code'){
            steps{
                echo "This is git source code"
            }
        }
        stage('packages'){
            steps{
                echo " this is maven package file1"
            }
        }
    }
}
